export const initialProperties = [
  {
    id: 1,
    name: "Lakeside Villa",
    type: "House",
    status: "Available",
    address: "25 Lakeview Dr",
  },
  {
    id: 2,
    name: "Ocean Breeze Apartments",
    type: "Apartment",
    status: "Available",
    address: "332 Shoreline Blvd",
  },
  {
    id: 3,
    name: "Mountain View Cabin",
    type: "House",
    status: "Rented",
    address: "56 Alpine Rd",
  },
  {
    id: 4,
    name: "Urban Studio Loft",
    type: "Apartment",
    status: "Available",
    address: "789 Downtown Ln",
  },
  {
    id: 5,
    name: "Greenwood Office Park",
    type: "Commercial",
    status: "Available",
    address: "400 Corporate Blvd",
  },
  {
    id: 6,
    name: "Coastal Retreat",
    type: "House",
    status: "Rented",
    address: "88 Ocean View Rd",
  },
  {
    id: 7,
    name: "Skyline Tower",
    type: "Apartment",
    status: "Available",
    address: "55 City Heights Ave",
  },
  {
    id: 8,
    name: "Silver Plaza Offices",
    type: "Commercial",
    status: "Rented",
    address: "120 Market St",
  },
  {
    id: 9,
    name: "Country Meadows Cottage",
    type: "House",
    status: "Available",
    address: "305 Countryside Dr",
  },
  {
    id: 10,
    name: "Riverside Complex",
    type: "Apartment",
    status: "Rented",
    address: "160 Riverbank Rd",
  },
];
